# Generated by Django 5.2.3 on 2025-08-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('subject_coordinator', 'Subject Coordinator'), ('principal', 'Principal')], default='teacher', max_length=20),
        ),
    ]
